# Generated by cucumber-sinatra. (Sun Feb 13 15:39:53 +0100 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Halet

class HaletWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  HaletWorld.new
end
